@hostName=localhost
@port=5184

### Create Resource A
# @name createResourceBRequest

POST http://{{hostName}}:{{port}}/api/v1/FunctionalDomainNameBLowerCase
Content-Type: application/json

{
    "someProperty": "fake content"
}

### Get ResourceB By Id
GET http://{{hostName}}:{{port}}/api/v1/FunctionalDomainNameBLowerCase/{{createResourceBRequest.response.body.$.id}}
