@hostName=localhost
@port=5184

### Create Resource A
# @name createResourceARequest

POST http://{{hostName}}:{{port}}/api/v1/FunctionalDomainNameALowerCase
Content-Type: application/json

{
    "someProperty": "fake content"
}

### Get ResourceA By Id
GET http://{{hostName}}:{{port}}/api/v1/FunctionalDomainNameALowerCase/{{createResourceARequest.response.body.$.id}}
