services:

  aspire-dashboard:
    image:  mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports: 
      - 18888:18888
      - 4317:18889

  # add service(s) for all your component dependencies